python -m mocapact.distillation.rollout_experts \
    --input_dirs ../data/experts/CMU_016_55-0-47 `# e.g., experts` \
    --bias_time 1.0 \
    --act_noise 0.05 \
    --termination_error_threshold 0.5 \
    --n_start_rollouts 100 \
    --n_rsi_rollouts 100 \
    --log_images \
    --output_path ../data/custom_rollouts_walk/file_name_ignored.hdf5 \
    --n_workers 1 `# e.g., 8` \
    --device cpu `# e.g., cuda` \
    --min_steps 70 \
    --ref_steps 1,2,3,4,5 \
    --separate_clips \
    --log_all_proprios \
    --nolog_cameras # set to True to log images from the cameras
